name: brainstorm_quest
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  inner_glow: ^1.0.0
  shared_preferences: ^2.3.1
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.1
  flutter_svg: ^2.0.10+1
  loading_indicator: ^3.1.1
  simple_gradient_text: ^1.3.0
  core_logic:
    git:
      url: https://github.com/Vennylost/core_logic.git
      ref: cf1c6788189d1391a15f2c64254f5b6198cc11f6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/fonts/
     - assets/json/
     - assets/generated/
  fonts:
    - family: Gulya
      fonts:
        - asset: assets/fonts/Gulya.otf
 